version: '3.7'

services: 
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: 
      - 9092:9092
    networks: 
      - kafka
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: 
      - kafka

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=jojonomic
      - POSTGRES_USER=adminpostgres
      - POSTGRES_PASSWORD=87654321
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump-jojonomic-202309011456.sql:/docker-entrypoint-initdb.d/jojonomic_dump.sql

      
networks:
  kafka: